name: Build on EC2
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # 这里指定使用 EC2 作为 runner
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          npm install

      - name: 编译项目
        run: |
          npm build
