name: Build on EC2
on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # 运行在 EC2
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 使用已有的 node_modules编译
        run: |
          ln -s /Users/nhg007/Documents/develop/smg/node_modules ./node_modules
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use v16.17.1
          npm run build

      - name: 删除服务器上的旧文件
        run: |
          ssh -i /Users/nhg007/Documents/aws/service-main.pem ubuntu@35.78.113.213 "rm -rf /home/ubuntu/vue-app/"

      - name: 直接上传 `dist/` 到服务器
        run: |
          scp -i /Users/nhg007/Documents/aws/service-main.pem -r dist/* ubuntu@35.78.113.213:/home/ubuntu/vue-app

      - name: 删除nginx-app配置文件
        run: |
          ssh -i /Users/nhg007/Documents/aws/service-main.pem ubuntu@35.78.113.213 "rm -f /etc/nginx/conf.d/app.conf"
      
      - name: 创建nginx-app配置文件
        run: |
          ssh -i /Users/nhg007/Documents/aws/service-main.pem ubuntu@35.78.113.213 << 'EOF'
          cat << | sudo tee /etc/nginx/sites-available/vue-app
          server {
              root /home/ubuntu/vue-app;
              index index.html;
              location / {
                  try_files \$uri /index.html;
              }
          }
          EOL
          # 创建符号链接，启用 Nginx 站点
          sudo ln -sf /etc/nginx/sites-available/vue-app /etc/nginx/sites-enabled/vue-app

          # 检查 Nginx 配置是否正确
          sudo nginx -t

          # 重新启动 Nginx
          sudo systemctl restart nginx
          EOF